# Generated by Django 6.0.2 on 2026-02-18 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_alter_clanmodel_system_name'),
        ('game', '0003_alter_bonusitemmodel_system_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBonusItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True, verbose_name='Count')),
                ('buy_count', models.IntegerField(null=True, verbose_name='Buy Count')),
                ('drop_count', models.IntegerField(null=True, verbose_name='Drop Count')),
                ('bonus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to='game.bonusitemmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('rid', models.CharField(max_length=15, unique=True, verbose_name='RID')),
                ('clan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='content.clanmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quests', models.IntegerField(default=0, null=True, verbose_name='Quests')),
                ('bonus_quests', models.IntegerField(default=0, null=True, verbose_name='Bonus Quests')),
                ('quests_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Quests Updated At')),
                ('money', models.IntegerField(default=0, verbose_name='Money')),
                ('health', models.IntegerField(default=0, verbose_name='Health')),
                ('strength', models.IntegerField(default=0, verbose_name='Strength')),
                ('vitality', models.IntegerField(default=0, verbose_name='Vitality')),
                ('share_used', models.BooleanField(default=False, verbose_name='Share Used')),
                ('damage_dealt', models.IntegerField(default=0, verbose_name='Damage Dealt')),
                ('damage_taken', models.IntegerField(default=0, verbose_name='Damage Taken')),
                ('block_count', models.IntegerField(default=0, verbose_name='Block Count')),
                ('code_fail_count', models.IntegerField(default=0, verbose_name='Code Fail Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Paused At')),
                ('pause_duration', models.IntegerField(null=True, verbose_name='Pause Duration')),
                ('quest_completed', models.BooleanField(null=True, verbose_name='Quests Completed')),
                ('status', models.SmallIntegerField(null=True, verbose_name='Status')),
                ('is_quest', models.BooleanField(default=False, verbose_name='Is Quest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
