# Generated by Django 6.0.2 on 2026-02-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('content', '0005_alter_clanmodel_system_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='remember_token',
            field=models.CharField(max_length=100, null=True, verbose_name='Remember Token'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='clan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ext', to='content.clanmodel'),
        ),
        migrations.DeleteModel(
            name='UserGames',
        ),
    ]
