# Generated by Django 6.0.2 on 2026-02-19 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userext_remember_token_alter_userext_clan_and_more'),
        ('game', '0003_alter_bonusitemmodel_system_name'),
        ('rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStagePrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
            ],
        ),
        migrations.AddField(
            model_name='userextra',
            name='money_gain',
            field=models.IntegerField(default=0, verbose_name='Money Gain'),
        ),
        migrations.AddField(
            model_name='userextra',
            name='money_spent',
            field=models.IntegerField(default=0, verbose_name='Money Spent'),
        ),
        migrations.AddField(
            model_name='userextra',
            name='tutorial_completed',
            field=models.BooleanField(default=False, verbose_name='Tutorial Completed'),
        ),
        migrations.AlterField(
            model_name='userbonusitems',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to='game.bonusitemmodel'),
        ),
        migrations.AlterField(
            model_name='userbonusitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userbonusitems',
            constraint=models.UniqueConstraint(fields=('user', 'bonus'), name='unique_user_bonus_item'),
        ),
        migrations.AddField(
            model_name='userstageprizes',
            name='stage_prize',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prizes', to='rating.stageprizesmodel'),
        ),
        migrations.AddField(
            model_name='userstageprizes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
