# Generated by Django 6.0.2 on 2026-02-19 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userstageprizes_userextra_money_gain_and_more'),
        ('game', '0003_alter_bonusitemmodel_system_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userbonusitems',
            name='unique_user_bonus_item',
        ),
        migrations.AddConstraint(
            model_name='userbonusitems',
            constraint=models.UniqueConstraint(fields=('user', 'bonus'), name='unique_user_bonus_item'),
        ),
    ]
