# Generated by Django 6.0.2 on 2026-02-19 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userbonusitems_unique_user_bonus_item_and_more'),
        ('content', '0005_alter_clanmodel_system_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('rid', models.CharField(max_length=15, unique=True, verbose_name='RID')),
                ('remember_token', models.CharField(max_length=100, null=True, verbose_name='Remember Token')),
                ('clan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='content.clanmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserExt',
        ),
    ]
