# Generated by Django 6.0.2 on 2026-02-19 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_delete_userext'),
        ('content', '0007_alter_faqmodel_position'),
        ('game', '0004_bonusitemlogmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userbonusitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbonusitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referral Code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Referred At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, db_column='referred_by_id', help_text='The user who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referred by'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='content.clanmodel', verbose_name='Clan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='remember_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remember Token'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbonusitems',
            index=models.Index(fields=['user', 'bonus'], name='account_use_user_id_143581_idx'),
        ),
        migrations.AddIndex(
            model_name='userbonusitems',
            index=models.Index(fields=['count'], name='account_use_count_2e7f64_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['uid'], name='idx_profile_uid'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['rid'], name='idx_profile_rid'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['referral_code'], name='idx_profile_ref_code'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['referred_by'], name='idx_profile_referred_by'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['clan'], name='idx_profile_clan'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['referred_at'], name='idx_profile_referred_at'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='idx_profile_created'),
        ),
    ]
