# Generated by Django 6.0.2 on 2026-02-19 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_alter_clanmodel_system_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('prize_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prize Date')),
                ('prize_description', models.TextField(blank=True, null=True, verbose_name='Prize Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='StagePrizesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stage_prizes', verbose_name='Image')),
                ('mini_image', models.ImageField(upload_to='stage_prizes', verbose_name='Mini Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Requirement')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Count')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rating.stagesmodel', verbose_name='Stage')),
            ],
        ),
        migrations.CreateModel(
            name='ClanRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_glory', models.IntegerField(verbose_name='Total Glory')),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clan_ratings', to='content.clanmodel', verbose_name='Clan')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clan_ratings', to='rating.stagesmodel', verbose_name='Stage')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glory', models.IntegerField(verbose_name='Glory')),
                ('glory_time', models.BigIntegerField(help_text='Timestamp for sorting', verbose_name='Glory Time')),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='content.clanmodel', verbose_name='Clan')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='rating.stagesmodel', verbose_name='Stage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'indexes': [models.Index(fields=['user'], name='idx_user_ratings_user_id'), models.Index(fields=['stage'], name='idx_user_ratings_stage_id'), models.Index(fields=['clan'], name='idx_user_ratings_clan_id'), models.Index(fields=['stage', '-glory', 'glory_time'], name='idx_user_ratings_global'), models.Index(fields=['stage', 'clan', '-glory', 'glory_time'], name='idx_user_ratings_clan')],
            },
        ),
    ]
