# Generated by Django 6.0.2 on 2026-02-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagesmodel',
            name='winners_sent',
            field=models.BooleanField(default=False, verbose_name='Winners Sent'),
        ),
        migrations.AlterField(
            model_name='stageprizesmodel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.stagesmodel', verbose_name='Stage'),
        ),
    ]
