# Generated by Django 6.0.2 on 2026-02-19 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Paused At')),
                ('pause_duration', models.IntegerField(null=True, verbose_name='Pause Duration')),
                ('quest_completed', models.BooleanField(null=True, verbose_name='Quests Completed')),
                ('status', models.SmallIntegerField(null=True, verbose_name='Status')),
                ('is_quest', models.BooleanField(default=False, verbose_name='Is Quest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
