# Generated by Django 6.0.2 on 2026-02-19 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_couponmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usergames',
            index=models.Index(fields=['started_at'], name='log_usergam_started_2f6f27_idx'),
        ),
        migrations.AddIndex(
            model_name='usergames',
            index=models.Index(fields=['started_at', 'user_id'], name='log_usergam_started_9ff37a_idx'),
        ),
    ]
