from .bonus_item import BonusItemAdmin
from .bonus_item_log import BonusItemLogAdmin
from .clan import ClanAdmin
from .clan_rating import ClanRatingAdmin
from .coupon import CouponAdmin
from .FAQ import FAQAdmin
from .game_setting import GameSettingModelAdmin
from .rule_image import RuleImageAdmin
from .sale import SalesAdmin
from .stage import StageAdmin
from .text import TextAdmin
from .user import UserProfileInline
from .user import UserBonusItemsInline
from .user import UserExtraInline
from .user import CustomUserAdmin
from .user_game import UserGamesAdmin
from .user_rating import UserRatingModelAdmin
