# Generated by Django 6.0.2 on 2026-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='Value')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='Description')),
            ],
        ),
    ]
