# Generated by Django 6.0.2 on 2026-02-26 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('system_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='System Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('reward', models.IntegerField(blank=True, null=True, verbose_name='Reward')),
                ('universal_coupon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universal coupon')),
                ('is_system', models.BooleanField(default=False, verbose_name='Is system')),
                ('is_shop', models.BooleanField(default=False, verbose_name='Is shop')),
                ('is_box', models.BooleanField(default=False, verbose_name='Is box')),
                ('chance', models.IntegerField(blank=True, null=True, verbose_name='Chance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Bonus item',
                'verbose_name_plural': 'Bonus items',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('system_name', models.CharField(max_length=255, null=True, verbose_name='System Name')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, null=True, verbose_name='Position')),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Question')),
                ('answer', models.TextField(max_length=2000, null=True, verbose_name='Answer')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='Value')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Game Settings',
                'verbose_name_plural': 'Game Settings',
            },
        ),
        migrations.CreateModel(
            name='RuleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Rule Image',
                'verbose_name_plural': 'Rule Images',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('prize_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prize Date')),
                ('prize_description', models.TextField(blank=True, null=True, verbose_name='Prize Description')),
                ('winners_sent', models.BooleanField(default=False, verbose_name='Winners Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Key')),
                ('text', models.TextField(max_length=2000, verbose_name='Value')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
            },
        ),
        migrations.CreateModel(
            name='BonusItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(blank=True, null=True, verbose_name='Source')),
                ('is_reserve', models.BooleanField(default=False, verbose_name='Is reserve')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bonus_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_item', to='game.bonusitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonus item source',
                'verbose_name_plural': 'Bonus items source',
            },
        ),
        migrations.CreateModel(
            name='ClanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_glory', models.IntegerField(verbose_name='Total Glory')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_ratings', to='game.clan', verbose_name='Clan')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_ratings', to='game.stage', verbose_name='Stage')),
            ],
        ),
        migrations.CreateModel(
            name='StagePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stage_prizes', verbose_name='Image')),
                ('mini_image', models.ImageField(upload_to='stage_prizes', verbose_name='Mini Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Requirement')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Count')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.stage', verbose_name='Stage')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quests', models.IntegerField(default=0, null=True, verbose_name='Quests')),
                ('bonus_quests', models.IntegerField(default=0, null=True, verbose_name='Bonus Quests')),
                ('quests_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Quests Updated At')),
                ('money', models.IntegerField(default=0, verbose_name='Money')),
                ('health', models.IntegerField(default=0, verbose_name='Health')),
                ('strength', models.IntegerField(default=0, verbose_name='Strength')),
                ('vitality', models.IntegerField(default=0, verbose_name='Vitality')),
                ('share_used', models.BooleanField(default=False, verbose_name='Share Used')),
                ('damage_dealt', models.IntegerField(default=0, verbose_name='Damage Dealt')),
                ('damage_taken', models.IntegerField(default=0, verbose_name='Damage Taken')),
                ('block_count', models.IntegerField(default=0, verbose_name='Block Count')),
                ('code_fail_count', models.IntegerField(default=0, verbose_name='Code Fail Count')),
                ('money_gain', models.IntegerField(default=0, verbose_name='Money Gain')),
                ('money_spent', models.IntegerField(default=0, verbose_name='Money Spent')),
                ('tutorial_completed', models.BooleanField(default=False, verbose_name='Tutorial Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Coupon Number')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('created', models.BooleanField(default=False, verbose_name='Created')),
                ('status', models.SmallIntegerField(null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'indexes': [models.Index(fields=['user'], name='game_coupon_user_id_b6693f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='UUID')),
                ('collection_name', models.CharField(max_length=255, verbose_name='Collection Name')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='MIME Type')),
                ('disk', models.CharField(max_length=255, verbose_name='Disk')),
                ('conversions_disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conversions Disk')),
                ('size', models.PositiveBigIntegerField(verbose_name='Size')),
                ('manipulations', models.JSONField(default=dict, verbose_name='Manipulations')),
                ('custom_properties', models.JSONField(default=dict, verbose_name='Custom Properties')),
                ('generated_conversions', models.JSONField(default=dict, verbose_name='Generated Conversions')),
                ('responsive_images', models.JSONField(default=dict, verbose_name='Responsive Images')),
                ('order_column', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Order Column')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['order_column', '-created_at'],
                'indexes': [models.Index(fields=['model_type', 'model_id'], name='game_media_model_t_79a7f3_idx'), models.Index(fields=['collection_name'], name='game_media_collect_c13cee_idx'), models.Index(fields=['disk'], name='game_media_disk_6f96fd_idx'), models.Index(fields=['order_column'], name='game_media_order_c_ef97a2_idx'), models.Index(fields=['created_at'], name='game_media_created_88c7ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBonusItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True, verbose_name='Count')),
                ('buy_count', models.IntegerField(null=True, verbose_name='Buy Count')),
                ('drop_count', models.IntegerField(null=True, verbose_name='Drop Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to='game.bonusitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'bonus'], name='game_userbo_user_id_90ab19_idx'), models.Index(fields=['count'], name='game_userbo_count_c6227c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'bonus'), name='unique_user_bonus_item')],
            },
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Paused At')),
                ('pause_duration', models.IntegerField(null=True, verbose_name='Pause Duration')),
                ('quest_completed', models.BooleanField(null=True, verbose_name='Quests Completed')),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Completed'), (2, 'Aborted'), (3, 'Paused')], null=True, verbose_name='Status')),
                ('is_quest', models.BooleanField(default=False, verbose_name='Is Quest')),
                ('platform', models.IntegerField(choices=[(10, 'Site'), (20, 'Application')], verbose_name='Platform')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game',
                'verbose_name_plural': 'User Games',
                'indexes': [models.Index(fields=['started_at'], name='game_userga_started_e82c64_idx'), models.Index(fields=['started_at', 'user_id'], name='game_userga_started_e4c08f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='UID')),
                ('rid', models.CharField(max_length=15, unique=True, verbose_name='RID')),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remember Token')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referral Code')),
                ('referred_at', models.DateTimeField(blank=True, null=True, verbose_name='Referred At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='game.clan', verbose_name='Clan')),
                ('referred_by', models.ForeignKey(blank=True, db_column='referred_by_id', help_text='The user who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referred by')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['uid'], name='idx_profile_uid'), models.Index(fields=['rid'], name='idx_profile_rid'), models.Index(fields=['referral_code'], name='idx_profile_ref_code'), models.Index(fields=['referred_by'], name='idx_profile_referred_by'), models.Index(fields=['clan'], name='idx_profile_clan'), models.Index(fields=['referred_at'], name='idx_profile_referred_at'), models.Index(fields=['created_at'], name='idx_profile_created')],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glory', models.IntegerField(verbose_name='Glory')),
                ('glory_time', models.BigIntegerField(help_text='Timestamp for sorting', verbose_name='Glory Time')),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='game.clan', verbose_name='Clan')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='game.stage', verbose_name='Stage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'indexes': [models.Index(fields=['user'], name='idx_user_ratings_user_id'), models.Index(fields=['stage'], name='idx_user_ratings_stage_id'), models.Index(fields=['clan'], name='idx_user_ratings_clan_id'), models.Index(fields=['stage', '-glory', 'glory_time'], name='idx_user_ratings_global'), models.Index(fields=['stage', 'clan', '-glory', 'glory_time'], name='idx_user_ratings_clan')],
            },
        ),
    ]
