# Generated by Django 6.0.2 on 2026-03-02 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanrating',
            options={'verbose_name': 'Clan rating', 'verbose_name_plural': 'Clans rating'},
        ),
        migrations.AlterField(
            model_name='usergames',
            name='pause_duration',
            field=models.IntegerField(default=0, verbose_name='Pause Duration'),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='platform',
            field=models.IntegerField(choices=[(0, 'site'), (1, 'application')], default=0, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='quest_completed',
            field=models.BooleanField(default=False, verbose_name='Quests Completed'),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'new'), (1, 'completed'), (2, 'aborted'), (3, 'paused')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
