# Generated by Django 6.0.2 on 2026-02-18 11:53

from django.db import migrations, models
from django.utils import timezone


def create_bonus_items(apps, schema_editor):
    BonusItem = apps.get_model('game', 'BonusItemModel')

    bonus_items_data = [
        {
            'position': 7,
            'title': 'Контракт',
            'system_name': 'contract',
            'description': 'Вы получили дополнительные контракт! Используйте его, чтобы получить больше славы и монет.',
            'price': None,
            'reward': 1,
            'universal_coupon': 'GAME22G000001',
            'is_system': True,
            'is_shop': True,
            'is_box': True,
            'chance': 10,
        },
        {
            'position': 1,
            'title': '150 славы',
            'system_name': 'glory',
            'description': 'Теперь ты выше в рейтинге и ближе к суперпризам',
            'price': None,
            'reward': 150,
            'universal_coupon': None,
            'is_system': True,
            'is_shop': False,
            'is_box': True,
            'chance': 10,
        },
        {
            'position': 4,
            'title': '50 монет',
            'system_name': 'money',
            'description': None,
            'price': None,
            'reward': 50,
            'universal_coupon': 'GAME22G000003',
            'is_system': True,
            'is_shop': False,
            'is_box': False,
            'chance': 0,
        },
        {
            'position': 5,
            'title': 'Волшебный сундук',
            'system_name': 'box',
            'description': None,
            'price': 1250,
            'reward': 1,
            'universal_coupon': 'GAME22G000008',
            'is_system': True,
            'is_shop': True,
            'is_box': False,
            'chance': 0,
        },
        {
            'position': 13,
            'title': 'Неигровой приз',
            'system_name': 'not_game_prize',
            'description': 'Приз, выдаваемый внешним сервисом, поле "Уникальный купон" используется как coupon_group для метода /activateCoupon',
            'price': None,
            'reward': None,
            'universal_coupon': 'Случайный для Игры',
            'is_system': True,
            'is_shop': False,
            'is_box': True,
            'chance': 10,
        },
        {
            'position': 0,
            'title': 'Здоровье',
            'system_name': 'health',
            'description': None,
            'price': 500,
            'reward': 1,
            'universal_coupon': None,
            'is_system': True,
            'is_shop': True,
            'is_box': False,
            'chance': 0,
        },
        {
            'position': 2,
            'title': 'Сила',
            'system_name': 'strength',
            'description': None,
            'price': 500,
            'reward': 1,
            'universal_coupon': None,
            'is_system': True,
            'is_shop': True,
            'is_box': False,
            'chance': 0,
        },
        {
            'position': 3,
            'title': 'Выносливость',
            'system_name': 'vitality',
            'description': None,
            'price': 500,
            'reward': 1,
            'universal_coupon': None,
            'is_system': True,
            'is_shop': True,
            'is_box': False,
            'chance': 0,
        },
    ]

    for item_data in bonus_items_data:
        BonusItem.objects.create(**item_data)


def remove_bonus_items(apps, schema_editor):
    BonusItem = apps.get_model('game', 'BonusItemModel')
    BonusItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]


    operations = [
        migrations.CreateModel(
            name='BonusItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('system_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='System name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('reward', models.IntegerField(blank=True, null=True, verbose_name='Reward')),
                ('universal_coupon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Universal coupon')),
                ('is_system', models.BooleanField(default=False, verbose_name='Is system')),
                ('is_shop', models.BooleanField(default=False, verbose_name='Is shop')),
                ('is_box', models.BooleanField(default=False, verbose_name='Is box')),
                ('chance', models.IntegerField(blank=True, null=True, verbose_name='Chance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Bonus item',
                'verbose_name_plural': 'Bonus items',
                'ordering': ['position'],
            },
        ),
        migrations.RunPython(create_bonus_items, remove_bonus_items),
        migrations.AlterModelOptions(
            name='gamesettingsmodel',
            options={'verbose_name': 'Game Settings', 'verbose_name_plural': 'Game Settings'},
        ),

    ]
