# Generated by Django 6.0.2 on 2026-03-04 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_clanrating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStagePrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
                ('stage_prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.stageprize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_prizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
