# Generated by Django 6.0.2 on 2026-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_bonusitemmodel_alter_gamesettingsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusitemmodel',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System Name'),
        ),
    ]
