# Generated by Django 6.0.2 on 2026-02-19 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_bonusitemmodel_system_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusItemLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(blank=True, null=True, verbose_name='Source')),
                ('is_reserve', models.BooleanField(default=False, verbose_name='Is reserve')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bonus_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_item', to='game.bonusitemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonus item source',
                'verbose_name_plural': 'Bonus items source',
            },
        ),
    ]
