# Generated by Django 6.0.1 on 2026-02-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='textmodel',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Text'),
        ),
    ]
