# Generated by Django 6.0.2 on 2026-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_textmodel_created_at_textmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('system_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
            },
        ),
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(max_length=2000, verbose_name='Answer')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='RuleImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Rule Image',
                'verbose_name_plural': 'Rule Images',
            },
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
