# Generated by Django 6.0.2 on 2026-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_clanmodel_faqmodel_ruleimagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmodel',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clanmodel',
            name='system_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clanmodel',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='answer',
            field=models.TextField(max_length=2000, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='position',
            field=models.IntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
    ]
