# Generated by Django 6.0.2 on 2026-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_clanmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmodel',
            name='system_name',
            field=models.CharField(max_length=255, null=True, verbose_name='System Name'),
        ),
    ]
