# Generated by Django 6.0.2 on 2026-02-19 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_clanmodel_system_name'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='UUID')),
                ('collection_name', models.CharField(max_length=255, verbose_name='Collection Name')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='MIME Type')),
                ('disk', models.CharField(max_length=255, verbose_name='Disk')),
                ('conversions_disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conversions Disk')),
                ('size', models.PositiveBigIntegerField(verbose_name='Size')),
                ('manipulations', models.JSONField(default=dict, verbose_name='Manipulations')),
                ('custom_properties', models.JSONField(default=dict, verbose_name='Custom Properties')),
                ('generated_conversions', models.JSONField(default=dict, verbose_name='Generated Conversions')),
                ('responsive_images', models.JSONField(default=dict, verbose_name='Responsive Images')),
                ('order_column', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Order Column')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Model Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['order_column', '-created_at'],
                'indexes': [models.Index(fields=['model_type', 'model_id'], name='content_med_model_t_450c26_idx'), models.Index(fields=['collection_name'], name='content_med_collect_27d60e_idx'), models.Index(fields=['disk'], name='content_med_disk_f75270_idx'), models.Index(fields=['order_column'], name='content_med_order_c_85afab_idx'), models.Index(fields=['created_at'], name='content_med_created_fb814d_idx')],
            },
        ),
    ]
