# Generated by Django 6.0.2 on 2026-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_mediamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='position',
            field=models.IntegerField(default=0, null=True, verbose_name='Position'),
        ),
    ]
