# Generated by Django 6.0.2 on 2026-04-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('drop_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Drop Video')),
                ('separate_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Separate Video')),
                ('info', models.TextField(null=True, verbose_name='Info')),
                ('hint', models.TextField(null=True, verbose_name='Hint')),
                ('cyclic_separate_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Cyclic Video')),
                ('processing_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Processing Video')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Level One',
                'verbose_name_plural': 'Level One',
            },
        ),
        migrations.CreateModel(
            name='LevelOneContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Type')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('info', models.TextField(null=True, verbose_name='Info')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_one_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelone', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Container',
            },
        ),
        migrations.CreateModel(
            name='LevelOneDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_one_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelone', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue',
                'verbose_name_plural': 'Dialogue',
            },
        ),
        migrations.CreateModel(
            name='LevelOneDialogueEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('earthquake', models.BooleanField(default=False, verbose_name='Earthquake')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_one_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelone', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue',
                'verbose_name_plural': 'Dialogue',
            },
        ),
    ]
