# Generated by Django 6.0.2 on 2026-04-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelonedialogueend',
            options={'verbose_name': 'Dialogue End', 'verbose_name_plural': 'Dialogue End'},
        ),
    ]
