# Generated by Django 6.0.2 on 2026-04-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_levelonedialogueend_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclic_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Cyclic Video')),
                ('background_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Processing Video')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Intro',
            },
        ),
        migrations.CreateModel(
            name='IntroDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('intro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.intro', verbose_name='Intro ID')),
            ],
            options={
                'verbose_name': 'Dialogue',
                'verbose_name_plural': 'Dialogue',
            },
        ),
    ]
