# Generated by Django 6.0.2 on 2026-04-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_intro_introdialogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Process Video')),
                ('cyclic_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Cyclic Video')),
                ('final_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Final Video')),
                ('reward_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Reward Video')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Level Three',
                'verbose_name_plural': 'Level Three',
            },
        ),
        migrations.CreateModel(
            name='LevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Hint Video')),
                ('transfer_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Transfer Video')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Level Two',
                'verbose_name_plural': 'Level Two',
            },
        ),
        migrations.CreateModel(
            name='LevelThreeDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_three_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelthree', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue Start',
                'verbose_name_plural': 'Dialogue Start',
            },
        ),
        migrations.CreateModel(
            name='LevelThreeDialogueEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_three_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelthree', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue End',
                'verbose_name_plural': 'Dialogue End',
            },
        ),
        migrations.CreateModel(
            name='LevelThreeDialogueExpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_three_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelthree', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue Expl',
                'verbose_name_plural': 'Dialogue Expl',
            },
        ),
        migrations.CreateModel(
            name='LevelThreeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_three_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelthree', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
            },
        ),
        migrations.CreateModel(
            name='LevelThreeResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Text')),
                ('description', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('process_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Process Video')),
                ('result_video', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Result Video')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_three_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelthree', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='LevelTwoDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_two_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.leveltwo', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue Start',
                'verbose_name_plural': 'Dialogue Start',
            },
        ),
        migrations.CreateModel(
            name='LevelTwoDialogueEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Image')),
                ('indicator', models.CharField(choices=[('normal', '20-70%'), ('excellent', '0-10%'), ('bad', '80-100%')], default='normal')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Updated at')),
                ('level_two_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.leveltwo', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Dialogue End',
                'verbose_name_plural': 'Dialogue End',
            },
        ),
    ]
